In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr_add = arr + 2
print("After adding 2 to all elements:", arr_add)

arr_multiply = arr * 3
print("After multiplying 3 with all elements:", arr_multiply)

arr_divide = arr / 2
print("After dividing each element by 2:", arr_divide)


After adding 2 to all elements: [3 4 5 6 7]
After multiplying 3 with all elements: [ 3  6  9 12 15]
After dividing each element by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

x = np.array([1,2,3,4,5,1,2,1,1,1])
unique_elements = np.unique(x)
print(unique_elements)

unique_values, counts = np.unique(x, return_counts=True)

most_frequent_value = unique_values[np.argmax(counts)]

indices = np.where(x == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique_values_y, counts_y = np.unique(y, return_counts=True)

most_frequent_value_y = unique_values_y[np.argmax(counts_y)]

indices_y = np.where(y == most_frequent_value_y)[0]

print(f"Most frequent value: {most_frequent_value_y}")
print(f"Indices: {indices_y}")


[5 4 6 3 2 1]
[1 2 3 4 5]
Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element_a = arr[0, 1]
print("Element at 1st row, 2nd column:", element_a)
element_b = arr[2, 0]
print("Element at 3rd row, 1st column:", element_b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [ ]:
balkaran = np.linspace(10, 100, 25)

print("Array:", balkaran)
print("Dimensions (ndim):", balkaran.ndim)
print("Shape:", balkaran.shape)
print("Total elements (size):", balkaran.size)
print("Data type (dtype):", balkaran.dtype)
print("Total bytes consumed (nbytes):", balkaran.nbytes)
transposed_array = balkaran.reshape(-1, 1)
print("Transposed array using reshape():\n", transposed_array)
transposed_array_T = balkaran.T
print("Transposed array using .T:\n", transposed_array_T)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200
Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
balkarans = np.array([[10, 20, 30, 40],
                      [50, 60, 70, 80],
                      [90, 15, 20, 35]])

mean_value = np.mean(balkarans)
median_value = np.median(balkarans)
max_value = np.max(balkarans)
min_value = np.min(balkarans)
unique_elements = np.unique(balkarans)

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Unique elements: {unique_elements}")

reshaped_balkarans = balkarans.reshape(4, 3)
print(f"Reshaped array (4 rows, 3 columns):\n{reshaped_balkarans}")

resized_balkarans = np.resize(balkarans, (2, 3))
print(f"Resized array (2 rows, 3 columns):\n{resized_balkarans}")


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4 rows, 3 columns):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2 rows, 3 columns):
[[10 20 30]
 [40 50 60]]


In [2]:
import numpy as np

ucs420_balkaran = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

mean_val = np.mean(ucs420_balkaran)
median_val = np.median(ucs420_balkaran)
max_val = np.max(ucs420_balkaran)
min_val = np.min(ucs420_balkaran)
unique_elements = np.unique(ucs420_balkaran)

reshaped_ucs420_balkaran = ucs420_balkaran.reshape(4, 3)

resized_ucs420_balkaran = np.resize(ucs420_balkaran, (2, 3))

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_elements)
print("Reshaped Array:\n", reshaped_ucs420_balkaran)
print("Resized Array:\n", resized_ucs420_balkaran)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
